version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: TicTacToeBank/Dockerfile
    container_name: tictactoe-bank-asp
    environment:
    - ASPNETCORE_URLS=http://+:8080
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__TicTacToeDbContext=Host=db;Port=5432;Database=tictactoe;Username=postgres;Password=123
    ports:
        - "5062:8080"
    depends_on:
        db:
          condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: tictactoe
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
        - app-network




networks:
  app-network:
    driver: bridge